<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Rohitha-Dell" failures="2" tests="10" name="Surefire test" time="174.818" errors="0" timestamp="2024-09-11T10:56:14 MDT">
  <testcase classname="RC.Tests.CartTests" name="checkCartProductsSameAsFoundItems" time="14.168"/>
  <testcase classname="RC.Tests.CartTests" name="checkCartProductsSameAsFoundItems" time="13.731"/>
  <testcase classname="RC.Tests.CartTests" name="checkTotal" time="12.806">
    <skipped/>
  </testcase> <!-- checkTotal -->
  <testcase classname="RC.Tests.CartTests" name="checkTotal" time="12.003">
    <skipped/>
  </testcase> <!-- checkTotal -->
  <testcase classname="RC.Tests.CartTests" name="checkTotal" time="11.809">
    <failure type="java.lang.AssertionError" message="expected [263000] but found [-263000]">
      <![CDATA[java.lang.AssertionError: expected [263000] but found [-263000]
at RC.Tests.CartTests.checkTotal(CartTests.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- checkTotal -->
  <testcase classname="RC.Tests.CartTests" name="checkTotal" time="11.27">
    <skipped/>
  </testcase> <!-- checkTotal -->
  <testcase classname="RC.Tests.CartTests" name="checkTotal" time="10.454">
    <skipped/>
  </testcase> <!-- checkTotal -->
  <testcase classname="RC.Tests.CartTests" name="checkTotal" time="15.906">
    <failure type="java.lang.AssertionError" message="expected [31500] but found [-31500]">
      <![CDATA[java.lang.AssertionError: expected [31500] but found [-31500]
at RC.Tests.CartTests.checkTotal(CartTests.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- checkTotal -->
  <testcase classname="RC.Tests.CartTests" name="printProductsCost" time="15.236"/>
  <testcase classname="RC.Tests.CartTests" name="printProductsCost" time="16.938"/>
</testsuite> <!-- Surefire test -->
